/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sk_pa3kc_mylibrary_cmd_CmdUtils */

#ifndef _Included_sk_pa3kc_mylibrary_cmd_CmdUtils
#define _Included_sk_pa3kc_mylibrary_cmd_CmdUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef sk_pa3kc_mylibrary_cmd_CmdUtils_escCode
#define sk_pa3kc_mylibrary_cmd_CmdUtils_escCode 27L
/*
 * Class:     sk_pa3kc_mylibrary_cmd_CmdUtils
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sk_pa3kc_mylibrary_cmd_CmdUtils_init(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
