/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sk_pa3kc_mylibrary_util_CmdColor */

#ifndef _Included_sk_pa3kc_mylibrary_util_CmdColor
#define _Included_sk_pa3kc_mylibrary_util_CmdColor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sk_pa3kc_mylibrary_util_CmdColor
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sk_pa3kc_mylibrary_util_CmdColor_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
