/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sk_pa3kc_mylibrary_util_FloatMath */

#ifndef _Included_sk_pa3kc_mylibrary_util_FloatMath
#define _Included_sk_pa3kc_mylibrary_util_FloatMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sk_pa3kc_mylibrary_util_FloatMath
 * Method:    sqrt
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_sk_pa3kc_mylibrary_util_FloatMath_sqrt(JNIEnv *, jclass, jfloat);

#ifdef __cplusplus
}
#endif
#endif
